spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.102/sells?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /Users/huangxin/Desktop/projects/IN_HOME/weChat/logs®
#  file: /Users/huangxin/Desktop/projects/IN_HOME/weChat/logs/sell.log
#  level:
#    com.sam.LoggerTest: debug
wechat:
  mpAppId: wxb9f5023f0ab41e6f
  mpAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://samcle.natapp1.cc/sell/pay/notify