spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.102/sells?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /Users/huangxin/Desktop/projects/IN_HOME/weChat/logs®
#  file: /Users/huangxin/Desktop/projects/IN_HOME/weChat/logs/sell.log
#  level:
#    com.sam.LoggerTest: debug